### ISSUE TITLE
All Item Types in Creating Shop items are Doubled, Items cant be added

### ISSUE THREAD

**Issue by Flowx3** [vBalatroni/preasyboard-issues#4]
![image](https://user-images.githubusercontent.com/26258408/211172784-cc46c4c9-50fc-4be0-bde8-8dd13b59e508.png)

Black line divide both Lists that are 1:1 the same but you still cannot use any of these it still says to check your Input
![image](https://user-images.githubusercontent.com/26258408/211172801-5f69a874-22de-42b0-b9bf-7b2099a41ce6.png)

Edit: No normal user should see this:
![image](https://user-images.githubusercontent.com/26258408/211172995-e4d249d5-f255-47ee-800e-4cfdf653c8bf.png)

Edit no2.
If you Import Characters while having none you get:
![image](https://user-images.githubusercontent.com/26258408/211173014-4452684d-0edc-4038-ab27-d5b51a156c5e.png)

I Currently get the same error if i wanna remove all roles from an account

**Comment by vBalatroni** [comment]
1. Doubled item types: was a problem with instantiation of item types, where called twice. Should be fixed on Game Dashboard creation
2. Was related to item types fields, i added a validation for upgrade and rarity but that validation was being called even when there were not upgrade nor rarity fields, should be ok
3. It's ok, that view will be both for admin and normal players, only have to define what normal player can see (any idea?)
4. Added a check on the api response to let it work properly,
